USE SQL_Task_db;
GO
CREATE VIEW Customer_Details AS 
SELECT CUSTOMER.Customer_Name, 
CUSTOMER.Street_Address, 
ORDER_DETAILS.Order_ID, 
ORDER_DETAILS.Order_Date, 
ORDER_DETAILS.Shipping_Type,
ORDER_DETAILS.Shopping_Cart_ID FROM CUSTOMER INNER JOIN ORDER_DETAILS ON ORDER_DETAILS.Customer_ID = CUSTOMER.Customer_ID WHERE CUSTOMER.Customer_ID = ''OR ''='';

GO
USE SQL_Task_db;
SELECT  PURCHASE_HISTORY.Customer_ID,ORDER_DETAILS.Order_ID, CUSTOMER.Customer_Name,SHOPPING_CART.Book_ID, BOOKS.Book_Name, ORDER_DETAILS.Order_Date, ORDER_DETAILS.Shopping_Cart_ID FROM PURCHASE_HISTORY 
INNER JOIN ORDER_DETAILS ON PURCHASE_HISTORY.Customer_ID = ORDER_DETAILS.Customer_ID
INNER JOIN SHOPPING_CART ON ORDER_DETAILS.Shopping_Cart_ID = SHOPPING_CART.Shopping_Cart_ID
INNER JOIN BOOKS ON BOOKS.Book_ID = SHOPPING_CART.Book_ID
INNER JOIN CUSTOMER ON ORDER_DETAILS.Customer_ID = CUSTOMER.Customer_ID